GalacticDynamics/coordinax

- src/vector/_transform.py
Fixes inference of the physical type.
> fix: dimensions in jacobian

- src/vector/_d4/spacetime.py
- src/vector/_typing.py
It meets the broadcasting requirement.
> fix: allow time to be a scalar in 4-vec

- src/vector/_base.py
> feat: differential times a Quantity

- src/coordinax/operators/_galilean/rotation.py
It’s triggering TracerBoolConversionError
> fix: temp remove SO(3) check

- tests/test_d3.py
At the origin, problems arise.
> fix: astropy tests

- pyproject.toml
- src/coordinax/_d1/builtin.py
- src/coordinax/_d2/builtin.py
- src/coordinax/_d3/sphere.py
- src/coordinax/_typing.py
Permits any distance class to be used for the distance.
> feat: allow any AbstractDistance as the distance

- src/coordinax/__init__.py
- src/coordinax/_base.py
- src/coordinax/_dn/__init__.py
- src/coordinax/_dn/base.py
- src/coordinax/_dn/builtin.py
- src/coordinax/_dn/transform.py
Followup tests will flesh out the transformations, etc.
> feat: NDCartesian

- src/coordinax/_dn/__init__.py
- src/coordinax/_dn/builtin.py
- src/coordinax/_dn/poincare.py
- src/coordinax/_dn/transform.py
- src/coordinax/_space.py
- src/coordinax/_transform/__init__.py
- src/coordinax/_transform/dn.py
- src/coordinax/_transform/space.py
Requires #135 to be able to transform between itself and other representations.
> Polar Poincare Vector

- pyproject.toml
- src/coordinax/setup_package.py
> refactor: runtime type-checking off by default

- pyproject.toml
- src/coordinax/_src/base/base.py
- src/coordinax/_src/base/mixins.py
- uv.lock
The components section of latex is only meh. Needs further formatting.
> feat: add IPython repr support

- pyproject.toml
- src/coordinax/_coordinax_space_frames/__init__.py
- src/coordinax/_coordinax_space_frames/_interop/__init__.py
- src/coordinax/_coordinax_space_frames/_interop/interop_astropy/__init__.py
- src/coordinax/_coordinax_space_frames/_interop/interop_astropy/frames.py
- src/coordinax/_coordinax_space_frames/_interop/optional_deps.py
- src/coordinax/_coordinax_space_frames/frame_transforms.py
- src/coordinax/_coordinax_space_frames/galactocentric.py
- src/coordinax/_coordinax_space_frames/icrs.py
- src/coordinax/_src/frames/base.py
- src/coordinax/frames.py
They are specific to astronomy and really should be in another package. I separate them into a different module for now.
> refactor: move space frames to separate module

- src/coordinax/_src/frames/errors.py
- src/coordinax/_src/frames/null.py
- src/coordinax/_src/frames/xfm.py
- src/coordinax/frames.py
> feat: no frame

- src/coordinax/_coordinax_space_frames/frame_transforms.py
- src/coordinax/_src/vectors/base/compat.py
This is also a breaking change.
> ✨ feat(vecs): uconvert mapping[str, ...] now has component, not dimension, keys

- src/coordinax/__init__.py
- src/coordinax/_interop/coordinax_interop_astropy/constructors.py
- src/coordinax/_src/frames/__init__.py
- src/coordinax/_src/frames/core.py
- src/coordinax/_src/operators/composite.py
- src/coordinax/_src/vectors/base/base.py
- src/coordinax/_src/vectors/space/core.py
- src/coordinax/frames.py
WIP.
The major thing to still figure out is how to represent the frame post-transformation. E.g. 
```python
import coordinax as cx
frame = cx.frames.ICRS()
data = cx.CartesianPos3D.from_([1, 2, 3], "kpc")
coord = cx.Coordinate(data, frame)
op = cx.operators.GalileanSpatialTranslationOperator.from_([1, 0, 0], "kpc")
newcoord = op(coord)
newcoord.frame  # What should that be? Maybe just an Operator?
```
> feat: coordinate

- src/coordinax/_src/utils.py
- src/coordinax/_src/vectors/base/base.py
- src/coordinax/_src/vectors/d3/cartesian.py
> 🚑️ hotfix(equality): fix equality comparison

- src/coordinax/_interop/coordinax_interop_astropy/constructors.py
Discovered in https://github.com/GalacticDynamics/galax/pull/520. I thought I found all necessary bugs in v0.17.2, but missed this one in the docs.
> 🐛 fix(vecs): vector from astropy quantity

- src/coordinax/_src/vectors/base/__init__.py
- src/coordinax/_src/vectors/base/cartesian.py
- src/coordinax/_src/vectors/d1/cartesian.py
- src/coordinax/_src/vectors/d2/cartesian.py
- src/coordinax/_src/vectors/d3/cartesian.py
- src/coordinax/_src/vectors/dn/__init__.py
- src/coordinax/_src/vectors/dn/cartesian.py
- src/coordinax/_src/vectors/dn/register_plum.py
- src/coordinax/_src/vectors/dn/register_vectorapi.py
Foundation for `tree-math` unified operations.
> ✨ feat(vecs): ABC Cartesian

- pyproject.toml
- src/coordinax/_src/custom_types.py
- src/coordinax/_src/distances/__init__.py
- src/coordinax/_src/distances/custom_types.py
- src/coordinax/_src/utils.py
- src/coordinax/_src/vectors/base/vector.py
- src/coordinax/_src/vectors/base_pos/core.py
- src/coordinax/_src/vectors/d1/cartesian.py
- src/coordinax/_src/vectors/d1/radial.py
- src/coordinax/_src/vectors/d2/cartesian.py
- src/coordinax/_src/vectors/d2/polar.py
- src/coordinax/_src/vectors/d2/spherical.py
- src/coordinax/_src/vectors/d3/cartesian.py
- src/coordinax/_src/vectors/d3/cylindrical.py
- src/coordinax/_src/vectors/d3/generic.py
- src/coordinax/_src/vectors/d3/lonlatspherical.py
- src/coordinax/_src/vectors/d3/mathspherical.py
- src/coordinax/_src/vectors/d3/spherical.py
- src/coordinax/_src/vectors/d3/spheroidal.py
- src/coordinax/_src/vectors/d4/spacetime.py
- src/coordinax/_src/vectors/dims.py
- src/coordinax/_src/vectors/dn/base.py
- src/coordinax/_src/vectors/dn/cartesian.py
- src/coordinax/_src/vectors/dn/poincare.py
- src/coordinax/_src/vectors/register_unxt.py
- src/coordinax/_src/vectors/register_vconvert/dn.py
- src/coordinax/_src/vectors/register_vconvert/space.py
- src/coordinax/_src/vectors/space/base.py
- src/coordinax/vecs.py
It would be nice to simplify this by parsing the fields! Then almost all could be determined from the type annotations.
> ✨ feat(vectors): add dimensions property

- pyproject.toml
- src/coordinax/_src/distances/base.py
- src/coordinax/_src/frames/register_vectorapi.py
- src/coordinax/_src/vectors/api.py
- src/coordinax/_src/vectors/base_vel/core.py
- src/coordinax/_src/vectors/custom_types.py
- src/coordinax/_src/vectors/d1/register_vectorapi.py
- src/coordinax/_src/vectors/d2/register_vectorapi.py
- src/coordinax/_src/vectors/d3/register_vectorapi.py
- src/coordinax/_src/vectors/d4/register_vectorapi.py
- src/coordinax/_src/vectors/dn/register_vectorapi.py
- src/coordinax/_src/vectors/private_api.py
- src/coordinax/_src/vectors/register_vconvert/__init__.py
- src/coordinax/_src/vectors/register_vconvert/common.py
- src/coordinax/_src/vectors/register_vconvert/d1.py
- src/coordinax/_src/vectors/register_vconvert/d2.py
- src/coordinax/_src/vectors/register_vconvert/d3.py
- src/coordinax/vecs.py
- tests/test_d2.py
- tests/test_d3.py
> ✨ feat(vectors): new low-level vconvert mechanism

- src/coordinax/_src/vectors/base/attribute.py
- src/coordinax/_src/vectors/base/vector.py
- src/coordinax/_src/vectors/base_acc/core.py
- src/coordinax/_src/vectors/base_pos/core.py
- src/coordinax/_src/vectors/base_pos/register_primitives.py
- src/coordinax/_src/vectors/base_vel/core.py
This enables +/- ProlateSpheroidalPos
> pass aux data through +/-

- docs/conventions.md
- docs/guides/coordinates_and_frames.md
- docs/guides/operators.md
- docs/guides/quantities.md
- docs/guides/vectors.md
- docs/index.md
This is a first PR from my initial look at the docs that mainly adds sphinx references to named classes, functions, and modules.
> Add sphinx references and some other minor tweaks

- src/coordinax/_interop/coordinax_interop_astropy/converters.py
- src/coordinax/_src/distances/measures.py
- src/coordinax/_src/distances/register_primitives.py
- src/coordinax/_src/vectors/checks.py
- src/coordinax/_src/vectors/d1/radial.py
- src/coordinax/_src/vectors/d2/polar.py
- src/coordinax/_src/vectors/d3/cylindrical.py
- src/coordinax/_src/vectors/d3/lonlatspherical.py
- src/coordinax/_src/vectors/d3/mathspherical.py
- src/coordinax/_src/vectors/d3/register_vectorapi.py
- src/coordinax/_src/vectors/d3/spherical.py
> ✨ feat(distance): non-negative

- README.md
- docs/guides/coordinates_and_frames.md
- docs/guides/vectors.md
- docs/index.md
- src/coordinax/__init__.py
- src/coordinax/_src/frames/coordinate.py
- src/coordinax/_src/frames/register_ops.py
- src/coordinax/_src/frames/register_vectorapi.py
- src/coordinax/_src/operators/compat.py
- src/coordinax/_src/vectors/base/base.py
- src/coordinax/_src/vectors/collection/__init__.py
- src/coordinax/_src/vectors/collection/core.py
- src/coordinax/_src/vectors/collection/register_dataclassish.py
- src/coordinax/_src/vectors/collection/register_primitives.py
- src/coordinax/_src/vectors/collection/register_vectorapi.py
- src/coordinax/_src/vectors/register_vconvert/collection.py
- src/coordinax/_src/vectors/register_vconvert/dn.py
- src/coordinax/vecs.py
- tests/test_d3.py
As discussed in coordinator meeting.
Followup PRs will clean up the code.
> 💥 boom(vecs): rename Space to KinematicSpace

- src/coordinax/_src/vectors/register_unxt.py
> ✨ feat(vecs): vector constructor
